package com.aceliq.frankfurt.models;

public enum UserState {
  MENU,
  CREATE_DECK_NAME,
  DELETE_DECK_NAME,
  DEFAULT, DECKMENU,
  MAINMENU,
  VIEW_DECK_NAME,
  CREATE_FRONT_CARD_NAME,
  CREATE_BACK_CARD_NAME,
  DELETE_CARD_NAME,
  CARDMENU,
  
}
